import React, { useState, useMemo } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import axios from 'axios';
import { useAuth } from './_contexts/AuthContext';
import { useTheme } from './_contexts/ThemeContext';

const BACKEND_URL = process.env.EXPO_PUBLIC_BACKEND_URL || 'http://localhost:8001';

type Section = 'menu' | 'terms' | 'privacy' | 'account';

const TERMS_OF_USE = `TERMS OF USE

Effective Date: 22 February 2026

Welcome to Kwanya, an AI-powered educational and conversational assistant designed primarily for Hausa-speaking users. These Terms of Use ("Terms") govern your access to and use of the Kwanya mobile application ("App"), operated by Trulib Ltd ("we," "us," or "our").

By downloading, accessing, or using Kwanya, you agree to be bound by these Terms. If you do not agree, please do not use the App.

1. ELIGIBILITY

You must be at least 13 years of age to use Kwanya. If you are under 18, you must have the consent of a parent or legal guardian. By using the App, you represent that you meet these requirements.

2. ACCOUNT REGISTRATION

To access certain features (e.g., credit purchases, conversation history), you may need to create an account using your phone number or email address. You agree to:

• Provide accurate and current information
• Keep your login credentials confidential
• Notify us immediately of any unauthorized access

We reserve the right to suspend or terminate accounts that violate these Terms.

3. DESCRIPTION OF SERVICES

Kwanya provides:
• AI-powered conversational assistance in Hausa and English
• Voice-to-text input (speech recognition)
• Text-based chat with an AI model
• A credit-based system for accessing AI features

The AI responses are generated by third-party language models (e.g., Google Gemini) and are not guaranteed to be accurate, complete, or suitable for any specific purpose.

4. CREDITS AND PAYMENTS

• Kwanya uses a credit-based system. Credits are required to send messages and use voice features.
• Credits can be purchased through the App using supported payment methods (e.g., Monnify).
• All purchases are final and non-refundable, except where required by applicable law.
• We reserve the right to change credit pricing at any time with reasonable notice.

5. ACCEPTABLE USE

You agree not to:
• Use the App for any illegal, harmful, or fraudulent purpose
• Attempt to reverse-engineer, decompile, or tamper with the App
• Upload or transmit malicious content, viruses, or harmful code
• Harass, abuse, or harm other users or our systems
• Use automated tools (bots, scrapers) to access the App
• Circumvent credit requirements or exploit system vulnerabilities

6. INTELLECTUAL PROPERTY

• All content, design, branding, and code within Kwanya are owned by Trulib Ltd or its licensors.
• You retain ownership of text and voice input you submit, but grant us a limited license to process it for providing the service.
• AI-generated responses are provided "as-is" and do not constitute our proprietary content or professional advice.

7. AI-GENERATED CONTENT DISCLAIMER

Kwanya uses artificial intelligence to generate responses. You acknowledge that:
• AI responses may contain errors, inaccuracies, or biased content
• AI output should not be relied upon as professional, legal, medical, or financial advice
• We do not guarantee the accuracy, reliability, or suitability of AI-generated content
• You use AI-generated content at your own risk

8. PRIVACY

Your use of the App is also governed by our Privacy Policy, which explains how we collect, use, and protect your data. By using the App, you consent to our data practices as described therein.

9. THIRD-PARTY SERVICES

Kwanya integrates with third-party services including:
• Google Gemini (AI model)
• Termii (SMS/Email verification)
• Monnify (payment processing)

We are not responsible for the practices or policies of these third-party providers.

10. LIMITATION OF LIABILITY

To the fullest extent permitted by law:
• Kwanya is provided "AS IS" and "AS AVAILABLE" without warranties of any kind.
• We are not liable for any indirect, incidental, consequential, or punitive damages arising from your use of the App.
• Our total liability shall not exceed the amount you paid to us in the 12 months preceding the claim.

11. INDEMNIFICATION

You agree to indemnify and hold harmless Trulib Ltd, its officers, directors, employees, and agents from any claims, damages, or expenses arising from your use of the App or violation of these Terms.

12. MODIFICATIONS TO THE TERMS

We may update these Terms from time to time. Changes will be posted within the App, and your continued use after such changes constitutes acceptance of the updated Terms. We encourage you to review these Terms periodically.

13. TERMINATION

We may suspend or terminate your access to the App at any time, with or without cause. Upon termination, your right to use the App ceases immediately. Sections that by their nature should survive termination (e.g., Limitation of Liability, Indemnification) will remain in effect.

14. GOVERNING LAW AND DISPUTE RESOLUTION

These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved through good-faith negotiation. If unresolved, disputes shall be submitted to binding arbitration under the Arbitration and Mediation Act of Nigeria.

15. CONTACT US

If you have questions about these Terms, please contact us at:

Trulib Ltd
Email: support@trulib.com`;

const PRIVACY_POLICY = `PRIVACY POLICY

Effective Date: 22 February 2026

Trulib Ltd ("we," "us," or "our") operates the Kwanya mobile application ("App"). This Privacy Policy explains how we collect, use, store, and protect your personal data when you use our App.

By using Kwanya, you agree to the practices described in this Privacy Policy.

1. INFORMATION WE COLLECT

a) Information You Provide:
• Phone number or email address (for account registration)
• One-Time Passwords (OTPs) for verification
• Text messages and voice recordings submitted during conversations
• Payment information processed through Monnify

b) Information Collected Automatically:
• Device type and operating system
• App usage data (e.g., session frequency, features used)
• Unique device identifiers
• Conversation metadata (timestamps, message counts)

c) Information from Third Parties:
• Payment confirmation data from Monnify
• Verification status from Termii (SMS/Email OTP provider)

2. HOW WE USE YOUR INFORMATION

We use your data to:
• Provide and improve AI-powered conversational services
• Verify your identity during registration and login
• Process credit purchases and manage your account balance
• Monitor usage for billing (credit deductions per message/voice input)
• Improve the quality and accuracy of our AI responses
• Ensure security and prevent fraud or abuse
• Comply with legal obligations

3. AI DATA PROCESSING

• Your text and voice inputs are sent to third-party AI models (e.g., Google Gemini) for generating responses.
• Voice inputs are processed using automatic speech recognition (ASR) to convert speech to text before being sent to the AI model.
• We may retain conversation history to maintain context within a session. Context is limited to the most recent messages per conversation.
• We do not use your personal conversations to train AI models.

4. DATA SHARING

We do not sell your personal data. We may share your data with:
• AI Service Providers (e.g., Google) — to process your queries
• Payment Processors (e.g., Monnify) — to handle transactions
• Communication Providers (e.g., Termii) — to send OTPs
• Law Enforcement — if required by law or to protect rights and safety

All third-party providers are bound by their own privacy policies and data protection obligations.

5. DATA RETENTION

• Account data: Retained as long as your account is active
• Conversation history: Stored to maintain context; may be deleted upon account deletion
• Payment records: Retained as required by financial regulations
• OTP data: Deleted immediately after verification

You may request deletion of your data by contacting us (see Section 11).

6. DATA SECURITY

We implement reasonable technical and organizational measures to protect your data, including:
• Encrypted data transmission (HTTPS/TLS)
• Secure storage of credentials and tokens
• Access controls on backend systems
• Regular security reviews

However, no system is completely secure, and we cannot guarantee absolute protection.

7. CHILDREN'S PRIVACY

Kwanya is not intended for children under the age of 13. We do not knowingly collect personal data from children under 13. If we discover such data has been collected, we will delete it promptly. Users between 13 and 18 must have parental or guardian consent.

8. YOUR RIGHTS

Depending on your jurisdiction, you may have the right to:
• Access the personal data we hold about you
• Request correction of inaccurate data
• Request deletion of your data
• Withdraw consent for data processing
• Object to certain types of data processing
• Request data portability

To exercise any of these rights, contact us at the details in Section 11.

9. COOKIES AND TRACKING

The Kwanya App does not use browser cookies. We may use local storage (e.g., AsyncStorage) on your device to maintain session data and preferences. This data remains on your device and is not transmitted to external tracking services.

10. CHANGES TO THIS POLICY

We may update this Privacy Policy from time to time. Any changes will be posted within the App, and your continued use constitutes acceptance of the updated policy. We encourage you to review this policy periodically.

11. CONTACT US

If you have questions, concerns, or requests regarding your privacy, please contact:

Trulib Ltd
Email: privacy@trulib.com

12. GOVERNING LAW

This Privacy Policy is governed by the laws of the Federal Republic of Nigeria, including the Nigeria Data Protection Regulation (NDPR) and any successor legislation.`;

export default function SettingsScreen() {
  const { palette } = useTheme();
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const { user, isAuthenticated, signOut, token } = useAuth();
  const [section, setSection] = useState<Section>('menu');
  const [isDeleting, setIsDeleting] = useState(false);

  const styles = useMemo(
    () =>
      StyleSheet.create({
        container: {
          flex: 1,
          backgroundColor: palette.bg,
          paddingTop: insets.top,
          paddingBottom: insets.bottom,
        },
        header: {
          flexDirection: 'row',
          alignItems: 'center',
          paddingHorizontal: 16,
          paddingVertical: 12,
          borderBottomWidth: 1,
          borderBottomColor: palette.border,
        },
        backButton: { padding: 4 },
        headerTitle: {
          fontSize: 20,
          fontWeight: '700',
          color: palette.text,
          marginLeft: 12,
        },
        scrollContent: { flex: 1 },
        menuSection: { paddingHorizontal: 20, paddingTop: 20 },
        menuItem: {
          flexDirection: 'row',
          alignItems: 'center',
          backgroundColor: palette.surface,
          borderRadius: 14,
          borderWidth: 1,
          borderColor: palette.border,
          paddingHorizontal: 16,
          paddingVertical: 16,
          marginBottom: 10,
        },
        menuItemText: {
          flex: 1,
          fontSize: 16,
          fontWeight: '600',
          color: palette.text,
          marginLeft: 12,
        },
        documentContent: {
          paddingHorizontal: 20,
          paddingVertical: 16,
        },
        documentText: {
          fontSize: 14,
          lineHeight: 22,
          color: palette.text,
        },
        accountSection: { paddingHorizontal: 20, paddingTop: 20 },
        accountItem: {
          flexDirection: 'row',
          alignItems: 'center',
          backgroundColor: palette.surface,
          borderRadius: 14,
          borderWidth: 1,
          borderColor: palette.border,
          paddingHorizontal: 16,
          paddingVertical: 16,
          marginBottom: 10,
        },
        accountItemDanger: {
          borderColor: '#FF3B30',
        },
        accountItemText: {
          flex: 1,
          fontSize: 16,
          fontWeight: '600',
          color: palette.text,
          marginLeft: 12,
        },
        accountItemTextDanger: {
          color: '#FF3B30',
        },
      }),
    [palette, insets],
  );

  const handleBack = () => {
    if (section !== 'menu') {
      setSection('menu');
    } else {
      router.replace({ pathname: '/', params: { sidebar: '1' } });
    }
  };

  const handleLogout = () => {
    Alert.alert(
      'Log Out',
      'Are you sure you want to log out?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Log Out',
          style: 'destructive',
          onPress: async () => {
            await signOut();
            router.replace('/');
          },
        },
      ],
    );
  };

  const handleDeleteAccount = () => {
    Alert.alert(
      'Delete Account',
      'This will permanently delete your account, all conversations, and credits. This action cannot be undone.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: () => {
            Alert.alert(
              'Are you absolutely sure?',
              'All your data will be permanently removed.',
              [
                { text: 'Cancel', style: 'cancel' },
                {
                  text: 'Yes, Delete My Account',
                  style: 'destructive',
                  onPress: async () => {
                    setIsDeleting(true);
                    try {
                      await axios.delete(`${BACKEND_URL}/api/auth/account`, {
                        headers: { Authorization: `Bearer ${token}` },
                      });
                      await signOut();
                      router.replace('/');
                    } catch {
                      Alert.alert('Error', 'Failed to delete account. Please try again.');
                    } finally {
                      setIsDeleting(false);
                    }
                  },
                },
              ],
            );
          },
        },
      ],
    );
  };

  const title =
    section === 'terms'
      ? 'Terms of Use'
      : section === 'privacy'
        ? 'Privacy Policy'
        : section === 'account'
          ? 'Account Settings'
          : 'Settings';

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={handleBack}>
          <Ionicons name="arrow-back" size={24} color={palette.text} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>{title}</Text>
      </View>

      {section === 'menu' && (
        <View style={styles.menuSection}>
          <TouchableOpacity
            style={styles.menuItem}
            onPress={() => setSection('terms')}
          >
            <Ionicons name="document-text-outline" size={22} color={palette.textMuted} />
            <Text style={styles.menuItemText}>Terms of Use</Text>
            <Ionicons name="chevron-forward" size={18} color={palette.textMuted} />
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.menuItem}
            onPress={() => setSection('privacy')}
          >
            <Ionicons name="shield-checkmark-outline" size={22} color={palette.textMuted} />
            <Text style={styles.menuItemText}>Privacy Policy</Text>
            <Ionicons name="chevron-forward" size={18} color={palette.textMuted} />
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.menuItem}
            onPress={() => setSection('account')}
          >
            <Ionicons name="person-outline" size={22} color={palette.textMuted} />
            <Text style={styles.menuItemText}>Account Settings</Text>
            <Ionicons name="chevron-forward" size={18} color={palette.textMuted} />
          </TouchableOpacity>
        </View>
      )}

      {section === 'account' && (
        <View style={styles.accountSection}>
          <TouchableOpacity style={styles.accountItem} onPress={handleLogout}>
            <Ionicons name="log-out-outline" size={22} color={palette.text} />
            <Text style={styles.accountItemText}>Log Out</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.accountItem, styles.accountItemDanger]}
            onPress={handleDeleteAccount}
            disabled={isDeleting}
          >
            {isDeleting ? (
              <ActivityIndicator size="small" color="#FF3B30" />
            ) : (
              <Ionicons name="trash-outline" size={22} color="#FF3B30" />
            )}
            <Text style={[styles.accountItemText, styles.accountItemTextDanger]}>
              Delete Account
            </Text>
          </TouchableOpacity>
        </View>
      )}

      {section === 'terms' && (
        <ScrollView
          style={styles.scrollContent}
          showsVerticalScrollIndicator={false}
          contentContainerStyle={styles.documentContent}
        >
          <Text style={styles.documentText} selectable>
            {TERMS_OF_USE}
          </Text>
        </ScrollView>
      )}

      {section === 'privacy' && (
        <ScrollView
          style={styles.scrollContent}
          showsVerticalScrollIndicator={false}
          contentContainerStyle={styles.documentContent}
        >
          <Text style={styles.documentText} selectable>
            {PRIVACY_POLICY}
          </Text>
        </ScrollView>
      )}
    </View>
  );
}
