import { Language } from './translations';

const TERMS_EN = `TERMS OF USE

Effective Date: 22 February 2026

Welcome to Kwanya, an AI-powered educational and conversational assistant designed primarily for Hausa-speaking users. These Terms of Use ("Terms") govern your access to and use of the Kwanya mobile application ("App"), operated by Trulib Ltd ("we," "us," or "our").

By downloading, accessing, or using Kwanya, you agree to be bound by these Terms. If you do not agree, please do not use the App.

1. ELIGIBILITY

You must be at least 13 years of age to use Kwanya. If you are under 18, you must have the consent of a parent or legal guardian. By using the App, you represent that you meet these requirements.

2. ACCOUNT REGISTRATION

To access certain features (e.g., credit purchases, conversation history), you may need to create an account using your phone number or email address. You agree to:

\u2022 Provide accurate and current information
\u2022 Keep your login credentials confidential
\u2022 Notify us immediately of any unauthorized access

We reserve the right to suspend or terminate accounts that violate these Terms.

3. DESCRIPTION OF SERVICES

Kwanya provides:
\u2022 AI-powered conversational assistance in Hausa and English
\u2022 Voice-to-text input (speech recognition)
\u2022 Text-based chat with an AI model
\u2022 A credit-based system for accessing AI features

The AI responses are generated by third-party language models (e.g., Google Gemini) and are not guaranteed to be accurate, complete, or suitable for any specific purpose.

4. CREDITS AND PAYMENTS

\u2022 Kwanya uses a credit-based system. Credits are required to send messages and use voice features.
\u2022 Credits can be purchased through the App using supported payment methods (e.g., Monnify).
\u2022 All purchases are final and non-refundable, except where required by applicable law.
\u2022 We reserve the right to change credit pricing at any time with reasonable notice.

5. ACCEPTABLE USE

You agree not to:
\u2022 Use the App for any illegal, harmful, or fraudulent purpose
\u2022 Attempt to reverse-engineer, decompile, or tamper with the App
\u2022 Upload or transmit malicious content, viruses, or harmful code
\u2022 Harass, abuse, or harm other users or our systems
\u2022 Use automated tools (bots, scrapers) to access the App
\u2022 Circumvent credit requirements or exploit system vulnerabilities

6. INTELLECTUAL PROPERTY

\u2022 All content, design, branding, and code within Kwanya are owned by Trulib Ltd or its licensors.
\u2022 You retain ownership of text and voice input you submit, but grant us a limited license to process it for providing the service.
\u2022 AI-generated responses are provided "as-is" and do not constitute our proprietary content or professional advice.

7. AI-GENERATED CONTENT DISCLAIMER

Kwanya uses artificial intelligence to generate responses. You acknowledge that:
\u2022 AI responses may contain errors, inaccuracies, or biased content
\u2022 AI output should not be relied upon as professional, legal, medical, or financial advice
\u2022 We do not guarantee the accuracy, reliability, or suitability of AI-generated content
\u2022 You use AI-generated content at your own risk

8. PRIVACY

Your use of the App is also governed by our Privacy Policy, which explains how we collect, use, and protect your data. By using the App, you consent to our data practices as described therein.

9. THIRD-PARTY SERVICES

Kwanya integrates with third-party services including:
\u2022 Google Gemini (AI model)
\u2022 Termii (SMS/Email verification)
\u2022 Monnify (payment processing)

We are not responsible for the practices or policies of these third-party providers.

10. LIMITATION OF LIABILITY

To the fullest extent permitted by law:
\u2022 Kwanya is provided "AS IS" and "AS AVAILABLE" without warranties of any kind.
\u2022 We are not liable for any indirect, incidental, consequential, or punitive damages arising from your use of the App.
\u2022 Our total liability shall not exceed the amount you paid to us in the 12 months preceding the claim.

11. INDEMNIFICATION

You agree to indemnify and hold harmless Trulib Ltd, its officers, directors, employees, and agents from any claims, damages, or expenses arising from your use of the App or violation of these Terms.

12. MODIFICATIONS TO THE TERMS

We may update these Terms from time to time. Changes will be posted within the App, and your continued use after such changes constitutes acceptance of the updated Terms. We encourage you to review these Terms periodically.

13. TERMINATION

We may suspend or terminate your access to the App at any time, with or without cause. Upon termination, your right to use the App ceases immediately. Sections that by their nature should survive termination (e.g., Limitation of Liability, Indemnification) will remain in effect.

14. GOVERNING LAW AND DISPUTE RESOLUTION

These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved through good-faith negotiation. If unresolved, disputes shall be submitted to binding arbitration under the Arbitration and Mediation Act of Nigeria.

15. CONTACT US

If you have questions about these Terms, please contact us at:

Trulib Ltd
Email: support@trulib.com`;

const TERMS_HA = `SHARUƊƊAN AMFANI

Ranar da ta fara aiki: 22 ga Fabrairu 2026

Barka da zuwa Kwanya, mataimakiyar tattaunawa da ilimi mai amfani da fasahar AI wacce aka tsara musamman don masu magana da Hausa. Waɗannan Sharuɗɗan Amfani ("Sharuɗɗa") suna tsara yadda za ku shiga da kuma amfani da manhajar wayar hannu ta Kwanya ("Manhaja"), wacce Trulib Ltd ("mu," "namu," ko "mu") ke gudanarwa.

Ta hanyar saukar da, shiga, ko amfani da Kwanya, kun yarda da waɗannan Sharuɗɗa. Idan ba ku yarda ba, da fatan kar ku yi amfani da Manhajar.

1. CANCANTAR SHIGA

Dole ne ku kasance da shekarun da ba su kasa da 13 ba don amfani da Kwanya. Idan kuna ƙasa da shekara 18, dole ne ku samu izinin iyaye ko mai kula da ku bisa doka. Ta hanyar amfani da Manhajar, kun tabbatar cewa kun cika waɗannan sharuɗɗa.

2. RAJISTA NA ASUSU

Don samun damar wasu ayyuka (misali, siyan kuɗi, tarihin hira), kuna iya buƙatar ƙirƙirar asusu ta hanyar lambar wayan ku ko adireshin imel. Kun yarda cewa:

\u2022 Za ku bayar da bayanan gaskiya kuma na yanzu
\u2022 Za ku kiyaye bayanan shiga na ku a asirce
\u2022 Za ku sanar da mu nan da nan game da kowane shiga ba tare da izini ba

Muna da ikon dakatar ko rufe asusun da suka keta waɗannan Sharuɗɗa.

3. BAYANIN AYYUKA

Kwanya tana bayarwa:
\u2022 Taimakon tattaunawa mai amfani da AI cikin Hausa da Turanci
\u2022 Shigar da murya zuwa rubutu (gane magana)
\u2022 Hira ta rubutu tare da ƙirar AI
\u2022 Tsarin kuɗi don samun damar ayyukan AI

Amsoshin AI na'urorin harshe na waje ne suka ƙirƙira su (misali, Google Gemini) kuma ba a tabbatar da cewa daidai ne, cikakku, ko dacewa da wani dalili na musamman ba.

4. KUƊI DA BIYA

\u2022 Kwanya tana amfani da tsarin kuɗi. Ana buƙatar kuɗi don aika saƙonni da amfani da ayyukan murya.
\u2022 Ana iya siyan kuɗi ta cikin Manhajar ta hanyar hanyoyin biya da ake tallafawa (misali, Monnify).
\u2022 Duk saye na ƙarshe ne kuma ba a mayar da su ba, sai dai inda doka ta buƙata.
\u2022 Muna da ikon canza farashin kuɗi a kowane lokaci tare da sanarwa mai ma'ana.

5. AMFANI DAIDAI

Kun yarda ba za ku:
\u2022 Yi amfani da Manhajar don wani dalili na haram, cutarwa, ko zamba
\u2022 Ƙoƙarin warware injiniya, tattara, ko lalata Manhajar
\u2022 Ɗora ko aika abubuwan cutarwa, ƙwayoyin cuta, ko lambar cutarwa
\u2022 Tsananta, cin zarafi, ko cutar da wasu masu amfani ko tsarinmu
\u2022 Yi amfani da kayan aiki na atomatik (bots, scrapers) don shiga Manhajar
\u2022 Ƙetare buƙatun kuɗi ko cin gajiyar raunin tsarin

6. MALLAKAR FASAHA

\u2022 Duk abubuwan da ke cikin Kwanya, tsari, alama, da lambar sun kasance mallakar Trulib Ltd ko masu ba ta lasisin.
\u2022 Kuna riƙe da mallakar rubutu da muryar da kuka aika, amma kun ba mu lasisin iyakance don sarrafa shi don bayar da sabis.
\u2022 Amsoshin da AI ta ƙirƙira an bayar da su "kamar yadda suke" kuma ba su zama abubuwan mallakarmu ko shawarar ƙwararru ba.

7. GARGAƊIN ABUBUWAN DA AI TA ƘIRƘIRA

Kwanya tana amfani da fasahar AI don ƙirƙirar amsoshi. Kun yarda cewa:
\u2022 Amsoshin AI na iya ƙunsar kurakurai, rashin daidaito, ko abubuwan da ke da son kai
\u2022 Ba a kamata a dogara da sakamakon AI a matsayin shawarar ƙwararru, shari'a, likita, ko kuɗi ba
\u2022 Ba mu tabbatar da daidaito, aminci, ko dacewa da abubuwan da AI ta ƙirƙira ba
\u2022 Kuna amfani da abubuwan da AI ta ƙirƙira a kan haɗarin ku

8. SIRRI

Amfanin ku da Manhajar kuma Manufar Sirri ce ke tsara shi, wacce ke bayyana yadda muke tattarawa, amfani, da kare bayanan ku. Ta hanyar amfani da Manhajar, kun yarda da ayyukan bayanan mu kamar yadda aka bayyana a cikinta.

9. AYYUKAN WASU KAMFANONI

Kwanya tana haɗa kai da ayyukan wasu kamfanoni ciki har da:
\u2022 Google Gemini (ƙirar AI)
\u2022 Termii (tabbatar da SMS/Imel)
\u2022 Monnify (sarrafa biya)

Ba mu da alhakin ayyuka ko manufofin waɗannan masu bayar da sabis na waje ba.

10. IYAKAR ALHAKIN

Har zuwa mafi girman iyakar da doka ta yarda:
\u2022 Ana bayar da Kwanya "KAMAR YADDA TAKE" kuma "KAMAR YADDA TAKE" ba tare da garanti na kowane iri ba.
\u2022 Ba mu da alhakin kowane barna kai tsaye, na haɗari, na sakamakon, ko na hukunci da ya taso daga amfanin ku da Manhajar.
\u2022 Jimlar alhakinmu ba za ta wuce adadin da kuka biya mana a cikin watanni 12 kafin buƙatar ba.

11. TABBATAR DA RASHIN LAIFI

Kun yarda da tabbatar da rashin laifin Trulib Ltd, jami'anta, daraktocinta, ma'aikatanta, da wakilanta daga kowane buƙatun, barna, ko kuɗin da ya taso daga amfanin ku da Manhajar ko keta waɗannan Sharuɗɗa.

12. GYARE-GYARE GA SHARUƊƊA

Za mu iya sabunta waɗannan Sharuɗɗa lokaci-lokaci. Za a buga canje-canje a cikin Manhajar, kuma ci gaba da amfani da ku bayan irin waɗannan canje-canje yana nufin yarda da Sharuɗɗan da aka sabunta. Muna ƙarfafa ku da ku duba waɗannan Sharuɗɗa akai-akai.

13. ƘAREWA

Za mu iya dakatar ko kawo ƙarshen damar ku na shiga Manhajar a kowane lokaci, tare da ko ba tare da dalili ba. Bayan ƙarewa, haƙƙin ku na amfani da Manhajar ya tsaya nan da nan. Sassan da bisa ɗabi'arsu ya kamata su tsira bayan ƙarewa (misali, Iyakar Alhakin, Tabbatar da Rashin Laifi) za su ci gaba da aiki.

14. DOKAR DA KE MULKI DA WARWARE RIKICI

Waɗannan Sharuɗɗa dokokin Jamhuriyar Tarayyar Nijeriya ne ke mulkinsu. Za a warware duk wani rikici ta hanyar tattaunawa cikin gaskiya. Idan ba a warware ba, za a miƙa rikice-rikice zuwa sasantawa mai ɗaure a ƙarƙashin Dokar Sasantawa da Sulhu ta Nijeriya.

15. TUNTUƁE MU

Idan kuna da tambayoyi game da waɗannan Sharuɗɗa, da fatan za a tuntuɓe mu a:

Trulib Ltd
Imel: support@trulib.com`;

const PRIVACY_EN = `PRIVACY POLICY

Effective Date: 22 February 2026

Trulib Ltd ("we," "us," or "our") operates the Kwanya mobile application ("App"). This Privacy Policy explains how we collect, use, store, and protect your personal data when you use our App.

By using Kwanya, you agree to the practices described in this Privacy Policy.

1. INFORMATION WE COLLECT

a) Information You Provide:
\u2022 Phone number or email address (for account registration)
\u2022 One-Time Passwords (OTPs) for verification
\u2022 Text messages and voice recordings submitted during conversations
\u2022 Payment information processed through Monnify

b) Information Collected Automatically:
\u2022 Device type and operating system
\u2022 App usage data (e.g., session frequency, features used)
\u2022 Unique device identifiers
\u2022 Conversation metadata (timestamps, message counts)

c) Information from Third Parties:
\u2022 Payment confirmation data from Monnify
\u2022 Verification status from Termii (SMS/Email OTP provider)

2. HOW WE USE YOUR INFORMATION

We use your data to:
\u2022 Provide and improve AI-powered conversational services
\u2022 Verify your identity during registration and login
\u2022 Process credit purchases and manage your account balance
\u2022 Monitor usage for billing (credit deductions per message/voice input)
\u2022 Improve the quality and accuracy of our AI responses
\u2022 Ensure security and prevent fraud or abuse
\u2022 Comply with legal obligations

3. AI DATA PROCESSING

\u2022 Your text and voice inputs are sent to third-party AI models (e.g., Google Gemini) for generating responses.
\u2022 Voice inputs are processed using automatic speech recognition (ASR) to convert speech to text before being sent to the AI model.
\u2022 We may retain conversation history to maintain context within a session. Context is limited to the most recent messages per conversation.
\u2022 We do not use your personal conversations to train AI models.

4. DATA SHARING

We do not sell your personal data. We may share your data with:
\u2022 AI Service Providers (e.g., Google) \u2014 to process your queries
\u2022 Payment Processors (e.g., Monnify) \u2014 to handle transactions
\u2022 Communication Providers (e.g., Termii) \u2014 to send OTPs
\u2022 Law Enforcement \u2014 if required by law or to protect rights and safety

All third-party providers are bound by their own privacy policies and data protection obligations.

5. DATA RETENTION

\u2022 Account data: Retained as long as your account is active
\u2022 Conversation history: Stored to maintain context; may be deleted upon account deletion
\u2022 Payment records: Retained as required by financial regulations
\u2022 OTP data: Deleted immediately after verification

You may request deletion of your data by contacting us (see Section 11).

6. DATA SECURITY

We implement reasonable technical and organizational measures to protect your data, including:
\u2022 Encrypted data transmission (HTTPS/TLS)
\u2022 Secure storage of credentials and tokens
\u2022 Access controls on backend systems
\u2022 Regular security reviews

However, no system is completely secure, and we cannot guarantee absolute protection.

7. CHILDREN'S PRIVACY

Kwanya is not intended for children under the age of 13. We do not knowingly collect personal data from children under 13. If we discover such data has been collected, we will delete it promptly. Users between 13 and 18 must have parental or guardian consent.

8. YOUR RIGHTS

Depending on your jurisdiction, you may have the right to:
\u2022 Access the personal data we hold about you
\u2022 Request correction of inaccurate data
\u2022 Request deletion of your data
\u2022 Withdraw consent for data processing
\u2022 Object to certain types of data processing
\u2022 Request data portability

To exercise any of these rights, contact us at the details in Section 11.

9. COOKIES AND TRACKING

The Kwanya App does not use browser cookies. We may use local storage (e.g., AsyncStorage) on your device to maintain session data and preferences. This data remains on your device and is not transmitted to external tracking services.

10. CHANGES TO THIS POLICY

We may update this Privacy Policy from time to time. Any changes will be posted within the App, and your continued use constitutes acceptance of the updated policy. We encourage you to review this policy periodically.

11. CONTACT US

If you have questions, concerns, or requests regarding your privacy, please contact:

Trulib Ltd
Email: privacy@trulib.com

12. GOVERNING LAW

This Privacy Policy is governed by the laws of the Federal Republic of Nigeria, including the Nigeria Data Protection Regulation (NDPR) and any successor legislation.`;

const PRIVACY_HA = `MANUFAR SIRRI

Ranar da ta fara aiki: 22 ga Fabrairu 2026

Trulib Ltd ("mu," "namu," ko "mu") tana gudanar da manhajar wayar hannu ta Kwanya ("Manhaja"). Wannan Manufar Sirri tana bayyana yadda muke tattarawa, amfani, adanawa, da kare bayanan ku na sirri lokacin da kuke amfani da Manhajar mu.

Ta hanyar amfani da Kwanya, kun yarda da ayyukan da aka bayyana a cikin wannan Manufar Sirri.

1. BAYANAI DA MUKE TATTARAWA

a) Bayanan da Kuke Bayarwa:
\u2022 Lambar waya ko adireshin imel (don rajista na asusu)
\u2022 Kalmomin Sirri na Lokaci Ɗaya (OTP) don tabbatarwa
\u2022 Saƙonnin rubutu da rikodin murya da aka aika yayin hira
\u2022 Bayanan biya da Monnify ke sarrafa

b) Bayanan da Ake Tattarawa ta Atomatik:
\u2022 Nau'in na'ura da tsarin aiki
\u2022 Bayanan amfani da Manhaja (misali, yawan zama, ayyukan da aka yi amfani da su)
\u2022 Alamomin na'ura na musamman
\u2022 Bayanan hira (lokutan, adadin saƙonni)

c) Bayanai daga Wasu Kamfanoni:
\u2022 Bayanan tabbatar da biya daga Monnify
\u2022 Matsayin tabbatarwa daga Termii (mai ba da OTP na SMS/Imel)

2. YADDA MUKE AMFANI DA BAYANAN KU

Muna amfani da bayanan ku don:
\u2022 Bayar da kuma inganta ayyukan tattaunawa masu amfani da AI
\u2022 Tabbatar da asalin ku yayin rajista da shiga
\u2022 Sarrafa siyan kuɗi da sarrafa ma'aunin asusun ku
\u2022 Sa ido kan amfani don biyan kuɗi (rage kuɗi ga kowane saƙo/shigar murya)
\u2022 Inganta inganci da daidaiton amsoshin AI namu
\u2022 Tabbatar da tsaro da hana zamba ko cin zarafi
\u2022 Bin dokokin da aka wajabta

3. SARRAFA BAYANAI NA AI

\u2022 Ana aika rubutun ku da shigar muryar ku zuwa ƙirar AI na waje (misali, Google Gemini) don ƙirƙirar amsoshi.
\u2022 Ana sarrafa shigar murya ta amfani da gane magana ta atomatik (ASR) don canza magana zuwa rubutu kafin a aika zuwa ƙirar AI.
\u2022 Za mu iya riƙe tarihin hira don kiyaye mahallin a cikin zama. Mahallin an iyakance shi zuwa saƙonnin da suka gabata a kowane hira.
\u2022 Ba mu amfani da hirarrakin ku na sirri don horar da ƙirar AI ba.

4. RABA BAYANAI

Ba mu sayar da bayanan ku na sirri ba. Za mu iya raba bayanan ku da:
\u2022 Masu Ba da Sabis na AI (misali, Google) \u2014 don sarrafa tambayoyin ku
\u2022 Masu Sarrafa Biya (misali, Monnify) \u2014 don gudanar da ma'amaloli
\u2022 Masu Ba da Sabis na Sadarwa (misali, Termii) \u2014 don aika OTP
\u2022 'Yan Sanda \u2014 idan doka ta buƙata ko don kare haƙƙoƙi da aminci

Duk masu ba da sabis na waje an ɗaure su da manufofin sirri da wajibcin kare bayanai na kansu.

5. RIƘE BAYANAI

\u2022 Bayanan asusu: Ana riƙe su muddin asusun ku yana aiki
\u2022 Tarihin hira: Ana adana shi don kiyaye mahallin; ana iya goge shi bayan goge asusu
\u2022 Rikodin biya: Ana riƙe su kamar yadda ka'idojin kuɗi suka buƙata
\u2022 Bayanan OTP: Ana goge su nan da nan bayan tabbatarwa

Kuna iya neman a goge bayanan ku ta hanyar tuntuɓar mu (duba Sashe na 11).

6. TSARON BAYANAI

Muna aiwatar da matakan fasaha da ƙungiya masu ma'ana don kare bayanan ku, ciki har da:
\u2022 Watsa bayanan da aka ɓoye (HTTPS/TLS)
\u2022 Adana bayanan shiga da alamomi cikin aminci
\u2022 Ikon shiga kan tsarin baya
\u2022 Bita na tsaro akai-akai

Koyaya, babu wani tsarin da ke cikakke mai aminci, kuma ba za mu iya tabbatar da kariya cikakkiya ba.

7. SIRRIN YARA

Ba a yi niyyar Kwanya ga yara ƙasa da shekara 13 ba. Ba mu sani ba muna tattara bayanan sirri na yara ƙasa da 13. Idan mun gano an tattara irin waɗannan bayanai, za mu goge su nan da nan. Masu amfani da suke tsakanin 13 da 18 dole ne su samu izinin iyaye ko mai kula.

8. HAƘƘOƘIN KU

Dangane da ikon shari'ar ku, kuna iya samun haƙƙin:
\u2022 Samun damar bayanan sirri da muke riƙe game da ku
\u2022 Neman gyara bayanan da ba daidai ba
\u2022 Neman a goge bayanan ku
\u2022 Janye izini don sarrafa bayanai
\u2022 Ƙin wasu nau'ikan sarrafa bayanai
\u2022 Neman ɗaukar bayanan ku zuwa wani wuri

Don amfani da kowane ɗaya daga cikin waɗannan haƙƙoƙi, tuntuɓe mu a bayanan da ke cikin Sashe na 11.

9. COOKIES DA SA IDO

Manhajar Kwanya ba ta amfani da cookies na yanar gizo ba. Za mu iya amfani da ajiyar gida (misali, AsyncStorage) a na'urar ku don kiyaye bayanan zama da zaɓuɓɓuka. Wannan bayanai yana ci gaba da zama a na'urar ku kuma ba a watsa shi zuwa ayyukan sa ido na waje ba.

10. CANJE-CANJE GA WANNAN MANUFA

Za mu iya sabunta wannan Manufar Sirri lokaci-lokaci. Za a buga duk wani canje-canje a cikin Manhajar, kuma ci gaba da amfani da ku yana nufin yarda da manufar da aka sabunta. Muna ƙarfafa ku da ku duba wannan manufar akai-akai.

11. TUNTUƁE MU

Idan kuna da tambayoyi, damuwa, ko buƙatu game da sirrin ku, da fatan za a tuntuɓi:

Trulib Ltd
Imel: privacy@trulib.com

12. DOKAR DA KE MULKI

Wannan Manufar Sirri dokokin Jamhuriyar Tarayyar Nijeriya ne ke mulkinta, ciki har da Ka'idar Kare Bayanai ta Nijeriya (NDPR) da kowane dokar da ta gaje ta.`;

export const legalDocuments: Record<Language, { termsOfUse: string; privacyPolicy: string }> = {
  en: {
    termsOfUse: TERMS_EN,
    privacyPolicy: PRIVACY_EN,
  },
  ha: {
    termsOfUse: TERMS_HA,
    privacyPolicy: PRIVACY_HA,
  },
};
